tls:
  certificates:
    - certFile: "/data/certificate.crt"
      keyFile: "/data/private.key"
      stores:
        - default

  stores:
    default:
      defaultCertificate:
        certFile: "/data/certificate.crt"
        keyFile: "/data/private.key"
